import Poster from '../../assets/ImgPoster.png';
import Age from '../../assets/Age.svg';
import TicketingBtn from '../../assets/TicketingBtn.svg';
import HeartBtn from '../../assets/HeartBtn.svg';

export const MovieData = [
  {
    id: 1,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 2,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 3,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 4,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 5,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 6,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 7,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 8,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 9,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 10,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 11,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
  {
    id: 12,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
  },
];
