import Poster from '../assets/ImgPoster.png';
import Age from '../assets/Age.svg';
import TicketingBtn from '../assets/TicketingBtn.svg';
import HeartBtn from '../assets/HeartBtn.svg';
import TicketingBtn1st from '../assets/TicketingBtnS.svg';
import CinemaBtn from '../assets/CinemaBtn.svg';

export const movieData = [
  {
    id: 1,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    ticketingBtn1st: TicketingBtn1st,
    cinemaBtn: CinemaBtn,
    isFirst: true,
  },
  {
    id: 2,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 3,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 4,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 5,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 6,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 7,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 8,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 9,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 10,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 11,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
  {
    id: 12,
    image: Poster,
    title: '극장판 짱구는 못말려:···',
    opingDate: '2022.09.28',
    ticketingRate: '0.9',
    ageImage: Age,
    ticketingBtn: TicketingBtn,
    heartBtn: HeartBtn,
    isFirst: false,
  },
];
